server:
  port: 8080
spring:
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: https://keycloak.popush.cloud/realms/Abyss
      client:
        registration:
          keycloak:
            client-id: ido-front
            # client-secret: from env
            provider: keycloak
            scope: openid
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/callback/{registrationId}'
        provider:
          keycloak:
            issuer-uri: https://keycloak.popush.cloud/realms/Abyss