server:
  port: 8080
spring:
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: https://keycloak.popush.cloud/realms/Abyss
      client:
        registration:
          keycloak:
            client-id: ido-front
            # client-secret: from env
            provider: keycloak
            scope: openid
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
        provider:
          keycloak:
            authorization-uri: https://keycloak.popush.cloud/realms/Abyss/protocol/openid-connect/auth
            token-uri: https://keycloak.popush.cloud/realms/Abyss/protocol/openid-connect/token
            user-info-uri: https://keycloak.popush.cloud/realms/Abyss/protocol/openid-connect/userinfo
            jwk-set-uri: https://keycloak.popush.cloud/realms/Abyss/protocol/openid-connect/certs
            user-name-attribute: preferred_username