name: deploy application

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      operation:
        description: '[app build]'
        required: false
jobs:
  build-job:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && (contains(github.event.head_commit.message, '[app build]') ||  contains(github.event.inputs.operation, '[app build]'))"
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 18
      - name: publish application docker to github packages
        run: |
          echo ${{ secrets.MY_GITHUB_TOKEN  }} | docker login ghcr.io -u matanki-saito --password-stdin
          ./gradlew docker dockerPush
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          GITHUB_USER_NAME: matanki.saito
      - name: update version and tagging
        run: |
          git config --local user.email "matanki.saito@gmail.com"
          git config --local user.name "matanki.saito"
          ./gradlew release -Prelease.useAutomaticVersion=true
